export interface Project {
  id: number;
  slug: string;
  title: string;
  category: string;
  description: string;
  longDescription: string;
  tags: string[];
  status: string;
  year: string;
  client: string;
  duration: string;
  features: string[];
  color: string;
  icon: string;
  image: string;
}

export const projects: Project[] = [
  {
    id: 1,
    slug: "ai-chatbot-platform",
    title: "AI Chatbot Platform",
    category: "AI & ML",
    description: "Intelligent customer support chatbot powered by GPT and custom ML models.",
    longDescription: "A next-generation AI chatbot platform that handles customer support 24/7 using advanced LLM technology.",
    tags: ["Next.js", "OpenAI", "Python", "TensorFlow"],
    status: "Completed",
    year: "2026",
    client: "TechCorp Inc.",
    duration: "3 months",
    features: ["24/7 automated customer support", "Multi-language support (10+ languages)", "Custom knowledge base integration", "Real-time sentiment analysis", "Analytics dashboard", "CRM integration"],
    color: "from-purple-600 via-violet-600 to-indigo-700",
    icon: "🤖",
    image: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 2,
    slug: "e-commerce-store",
    title: "E-Commerce Store",
    category: "E-Commerce",
    description: "Full-featured online store with payment gateway and inventory management.",
    longDescription: "A complete e-commerce solution with modern UI, secure payments, and powerful admin dashboard.",
    tags: ["React", "Stripe", "Node.js", "PostgreSQL"],
    status: "Completed",
    year: "2026",
    client: "ShopEasy",
    duration: "4 months",
    features: ["Secure payment gateway", "Product catalog with search", "Shopping cart & wishlist", "Order tracking system", "Admin dashboard", "Multi-currency support"],
    color: "from-orange-500 via-amber-500 to-yellow-600",
    icon: "🛒",
    image: "https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 3,
    slug: "food-delivery-app",
    title: "Food Delivery App",
    category: "Mobile Apps",
    description: "Cross-platform mobile app for food ordering with real-time tracking.",
    longDescription: "A modern food delivery mobile application featuring real-time GPS tracking and multiple payment options.",
    tags: ["React Native", "Firebase", "Maps API"],
    status: "Completed",
    year: "2026",
    client: "QuickBite",
    duration: "5 months",
    features: ["Real-time order tracking", "Multiple restaurant support", "In-app payments", "Push notifications", "Rating & reviews", "Chat with driver"],
    color: "from-green-500 via-emerald-500 to-teal-600",
    icon: "🍔",
    image: "https://images.pexels.com/photos/4393021/pexels-photo-4393021.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 4,
    slug: "saas-analytics-dashboard",
    title: "SaaS Analytics Dashboard",
    category: "Web Development",
    description: "Analytics dashboard for SaaS companies with real-time data visualization.",
    longDescription: "An enterprise-grade analytics dashboard helping SaaS companies track KPIs and revenue.",
    tags: ["Next.js", "Chart.js", "PostgreSQL", "Prisma"],
    status: "Completed",
    year: "2026",
    client: "DataFlow",
    duration: "3 months",
    features: ["Real-time data visualization", "Custom report builder", "Team collaboration", "Export to PDF/CSV", "API access", "Role-based access control"],
    color: "from-blue-600 via-cyan-600 to-teal-600",
    icon: "📊",
    image: "https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 5,
    slug: "healthcare-portal",
    title: "Healthcare Portal",
    category: "Web Development",
    description: "Patient management system with appointment booking and telemedicine.",
    longDescription: "A comprehensive healthcare portal connecting patients with doctors for online consultations.",
    tags: ["React", "Node.js", "MongoDB", "WebRTC"],
    status: "Completed",
    year: "2026",
    client: "MediCare Plus",
    duration: "6 months",
    features: ["Video consultations", "Appointment scheduling", "Medical records management", "Prescription management", "Patient-doctor chat", "HIPAA compliant"],
    color: "from-cyan-500 via-sky-500 to-blue-600",
    icon: "🏥",
    image: "https://images.pexels.com/photos/40568/medical-appointment-doctor-healthcare-40568.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 6,
    slug: "creative-agency-portfolio",
    title: "Creative Agency Portfolio",
    category: "UI/UX Design",
    description: "Modern, animated portfolio for creative agencies with CMS integration.",
    longDescription: "A stunning portfolio website for creative agencies featuring award-winning animations.",
    tags: ["Next.js", "Framer Motion", "Sanity CMS"],
    status: "Completed",
    year: "2026",
    client: "Pixel Studio",
    duration: "2 months",
    features: ["Award-winning animations", "Smooth scroll interactions", "Headless CMS", "Case studies section", "Blog integration", "Contact form with validation"],
    color: "from-pink-500 via-rose-500 to-red-600",
    icon: "🎨",
    image: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 7,
    slug: "ai-image-generator",
    title: "AI Image Generator",
    category: "AI & ML",
    description: "Text-to-image generation platform using Stable Diffusion models.",
    longDescription: "A powerful AI image generation platform allowing users to create stunning artwork.",
    tags: ["Python", "FastAPI", "React", "Stable Diffusion"],
    status: "Completed",
    year: "2026",
    client: "ArtGen AI",
    duration: "4 months",
    features: ["Text-to-image generation", "Multiple art styles", "Image upscaling", "Batch generation", "Gallery management", "API for developers"],
    color: "from-indigo-600 via-purple-600 to-violet-700",
    icon: "🎭",
    image: "https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 8,
    slug: "fitness-tracking-app",
    title: "Fitness Tracking App",
    category: "Mobile Apps",
    description: "Personal fitness tracker with workout plans and health insights.",
    longDescription: "A comprehensive fitness tracking mobile app with personalized workout plans.",
    tags: ["React Native", "Health API", "Firebase"],
    status: "Completed",
    year: "2026",
    client: "FitLife",
    duration: "5 months",
    features: ["Workout tracking", "Nutrition logging", "Wearable integration", "Progress analytics", "Social challenges", "Personalized plans"],
    color: "from-emerald-500 via-green-500 to-teal-600",
    icon: "💪",
    image: "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 9,
    slug: "corporate-website",
    title: "Corporate Website",
    category: "Web Development",
    description: "Professional corporate website with multi-language support.",
    longDescription: "A modern corporate website built for a global company featuring multi-language support.",
    tags: ["Next.js", "i18n", "Tailwind", "SEO"],
    status: "Completed",
    year: "2026",
    client: "GlobalCorp",
    duration: "3 months",
    features: ["Multi-language (5 languages)", "Advanced SEO optimization", "Blog & news section", "Careers portal", "Team directory", "Contact forms"],
    color: "from-slate-700 via-gray-700 to-zinc-800",
    icon: "🏢",
    image: "https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 10,
    slug: "crypto-trading-bot",
    title: "Crypto Trading Bot",
    category: "AI & ML",
    description: "Automated cryptocurrency trading bot with ML-powered predictions.",
    longDescription: "An intelligent crypto trading bot using machine learning algorithms.",
    tags: ["Python", "TensorFlow", "Binance API"],
    status: "In Progress",
    year: "2026",
    client: "CryptoPro",
    duration: "6 months",
    features: ["ML-based predictions", "Multi-exchange support", "Risk management", "Backtesting engine", "Real-time alerts", "Performance analytics"],
    color: "from-amber-500 via-yellow-500 to-orange-600",
    icon: "📈",
    image: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 11,
    slug: "learning-management-system",
    title: "Learning Management System",
    category: "Web Development",
    description: "Complete LMS with video courses, quizzes, and student tracking.",
    longDescription: "A full-featured learning management system for online education platforms.",
    tags: ["Next.js", "Prisma", "Mux", "PostgreSQL"],
    status: "Completed",
    year: "2026",
    client: "EduTech Pro",
    duration: "7 months",
    features: ["Video course hosting", "Interactive quizzes", "Student progress tracking", "Certificate generation", "Payment integration", "Discussion forums"],
    color: "from-teal-500 via-cyan-500 to-blue-600",
    icon: "📚",
    image: "https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 12,
    slug: "real-estate-marketplace",
    title: "Real Estate Marketplace",
    category: "Web Development",
    description: "Modern marketplace connecting buyers, sellers, and real estate agents.",
    longDescription: "A comprehensive real estate platform with advanced property search and virtual tours.",
    tags: ["Next.js", "Mapbox", "Stripe", "MongoDB"],
    status: "Coming Soon",
    year: "2026",
    client: "HomeFinder",
    duration: "8 months",
    features: ["Advanced property search", "Virtual 3D tours", "Mortgage calculator", "Agent dashboard", "Map integration", "Saved favorites"],
    color: "from-rose-500 via-pink-500 to-fuchsia-600",
    icon: "🏠",
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}