export interface Service {
  id: number;
  slug: string;
  title: string;
  shortTitle: string;
  category: string;
  description: string;
  longDescription: string;
  icon: string;
  color: string;
  image: string;
  features: string[];
  technologies: string[];
  process: { step: string; description: string }[];
  benefits: string[];
  pricing: string;
  duration: string;
}

export const services: Service[] = [
  {
    id: 1,
    slug: "ai-machine-learning",
    title: "AI & Machine Learning",
    shortTitle: "AI & ML",
    category: "AI",
    description: "Automate workflows, uncover insights, and accelerate innovation with AI-powered applications.",
    longDescription: "We build custom AI and machine learning solutions tailored to your business needs — from intelligent chatbots and recommendation engines to predictive analytics and computer vision systems.",
    icon: "🧠",
    color: "from-purple-600 via-violet-600 to-indigo-700",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&q=80",
    features: [
      "Custom AI model development",
      "Natural Language Processing (NLP)",
      "Computer Vision systems",
      "Predictive analytics",
      "Recommendation engines",
      "AI chatbots & virtual assistants",
      "Machine learning pipelines",
      "Model training & optimization",
    ],
    technologies: ["Python", "TensorFlow", "PyTorch", "OpenAI", "Hugging Face", "Scikit-learn"],
    process: [
      { step: "Discovery", description: "We understand your business problem and data" },
      { step: "Data Preparation", description: "Clean, structure, and prepare your data" },
      { step: "Model Development", description: "Build and train custom AI models" },
      { step: "Testing & Optimization", description: "Rigorous testing and fine-tuning" },
      { step: "Deployment", description: "Deploy to production with monitoring" },
    ],
    benefits: [
      "Reduce operational costs by up to 60%",
      "Process data 100x faster than manual",
      "24/7 intelligent automation",
      "Scalable to millions of users",
    ],
    pricing: "Starting from $5,000",
    duration: "4-12 weeks",
  },
  {
    id: 2,
    slug: "web-development",
    title: "Web Development",
    shortTitle: "Web Dev",
    category: "Web",
    description: "Create responsive, high-performance websites that engage your audience and boost conversions.",
    longDescription: "We build modern, fast, and scalable web applications using the latest technologies — from marketing websites and SaaS platforms to complex enterprise applications.",
    icon: "💻",
    color: "from-blue-600 via-cyan-600 to-teal-600",
    image: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=1200&q=80",
    features: [
      "Custom website development",
      "Progressive Web Apps (PWA)",
      "E-commerce platforms",
      "SaaS applications",
      "Content Management Systems",
      "API development & integration",
      "SEO optimization",
      "Performance optimization",
    ],
    technologies: ["Next.js", "React", "Node.js", "TypeScript", "Tailwind CSS", "PostgreSQL"],
    process: [
      { step: "Planning", description: "Define scope, features, and architecture" },
      { step: "Design", description: "Create wireframes and UI mockups" },
      { step: "Development", description: "Build the frontend and backend" },
      { step: "Testing", description: "QA, bug fixes, and performance tuning" },
      { step: "Launch", description: "Deploy and monitor the live site" },
    ],
    benefits: [
      "Lightning-fast page load times",
      "Mobile-responsive on all devices",
      "SEO-optimized for search engines",
      "Scalable architecture",
    ],
    pricing: "Starting from $2,000",
    duration: "2-8 weeks",
  },
  {
    id: 3,
    slug: "mobile-app-development",
    title: "Mobile App Development",
    shortTitle: "Mobile Apps",
    category: "Mobile",
    description: "Deliver seamless mobile experiences that increase customer engagement and brand loyalty.",
    longDescription: "We create native and cross-platform mobile applications for iOS and Android that deliver exceptional user experiences and drive business growth.",
    icon: "📱",
    color: "from-green-500 via-emerald-500 to-teal-600",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&q=80",
    features: [
      "iOS app development",
      "Android app development",
      "Cross-platform apps (React Native)",
      "App Store optimization",
      "Push notifications",
      "In-app purchases",
      "Offline functionality",
      "App analytics",
    ],
    technologies: ["React Native", "Flutter", "Swift", "Kotlin", "Firebase", "Expo"],
    process: [
      { step: "Concept", description: "Define app features and user flow" },
      { step: "UI/UX Design", description: "Design beautiful mobile interfaces" },
      { step: "Development", description: "Build iOS and Android apps" },
      { step: "Testing", description: "Test on real devices" },
      { step: "Store Launch", description: "Submit to App Store & Play Store" },
    ],
    benefits: [
      "Native performance on both platforms",
      "App store ready deployment",
      "Push notification engagement",
      "Real-time analytics",
    ],
    pricing: "Starting from $4,000",
    duration: "4-12 weeks",
  },
  {
    id: 4,
    slug: "ui-ux-design",
    title: "UX/UI Design",
    shortTitle: "UI/UX",
    category: "Design",
    description: "Design intuitive interfaces that provide smooth, enjoyable user experiences.",
    longDescription: "We create beautiful, user-centered designs that not only look great but also drive conversions and delight your users.",
    icon: "🎨",
    color: "from-pink-500 via-rose-500 to-red-600",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&q=80",
    features: [
      "User research & personas",
      "Wireframing & prototyping",
      "Visual design & branding",
      "Design systems",
      "Interaction design",
      "Usability testing",
      "Accessibility design",
      "Mobile-first design",
    ],
    technologies: ["Figma", "Adobe XD", "Sketch", "Framer", "Principle", "Maze"],
    process: [
      { step: "Research", description: "Understand users and business goals" },
      { step: "Wireframes", description: "Sketch low-fidelity layouts" },
      { step: "Prototype", description: "Build interactive prototypes" },
      { step: "Testing", description: "Test with real users" },
      { step: "Handoff", description: "Deliver developer-ready designs" },
    ],
    benefits: [
      "Increase conversions by up to 200%",
      "Reduce user friction",
      "Build brand recognition",
      "Developer-ready design systems",
    ],
    pricing: "Starting from $1,500",
    duration: "2-6 weeks",
  },
  {
    id: 5,
    slug: "cloud-devops",
    title: "Cloud & DevOps",
    shortTitle: "Cloud & DevOps",
    category: "Cloud",
    description: "Scalable cloud infrastructure on AWS, Azure, GCP with automated CI/CD pipelines.",
    longDescription: "We architect, deploy, and manage cloud infrastructure that scales with your business — with automated pipelines, monitoring, and security best practices.",
    icon: "☁️",
    color: "from-sky-500 via-cyan-500 to-blue-600",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&q=80",
    features: [
      "Cloud architecture design",
      "AWS/Azure/GCP setup",
      "CI/CD pipelines",
      "Container orchestration (Kubernetes)",
      "Infrastructure as Code",
      "Monitoring & alerting",
      "Cost optimization",
      "Security & compliance",
    ],
    technologies: ["AWS", "Docker", "Kubernetes", "Terraform", "GitHub Actions", "Vercel"],
    process: [
      { step: "Assessment", description: "Audit current infrastructure" },
      { step: "Architecture", description: "Design cloud architecture" },
      { step: "Migration", description: "Move workloads to cloud" },
      { step: "Automation", description: "Set up CI/CD pipelines" },
      { step: "Monitoring", description: "Set up monitoring & alerts" },
    ],
    benefits: [
      "99.9% uptime guarantee",
      "Reduce cloud costs by 40%",
      "Auto-scaling infrastructure",
      "Enterprise-grade security",
    ],
    pricing: "Starting from $3,000",
    duration: "3-8 weeks",
  },
  {
    id: 6,
    slug: "data-engineering",
    title: "Data Engineering",
    shortTitle: "Data Engineering",
    category: "Data",
    description: "Unlock the full potential of your data with scalable infrastructure and streamlined pipelines.",
    longDescription: "We build data pipelines and infrastructure that help you collect, process, and analyze data at scale — turning raw data into actionable insights.",
    icon: "🗄️",
    color: "from-orange-500 via-amber-500 to-yellow-600",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    features: [
      "Data pipeline development",
      "ETL/ELT processes",
      "Data warehousing",
      "Real-time streaming",
      "Data quality & governance",
      "Database optimization",
      "Data lake architecture",
      "API integrations",
    ],
    technologies: ["Python", "Apache Spark", "Airflow", "Snowflake", "BigQuery", "Kafka"],
    process: [
      { step: "Assessment", description: "Review data sources and needs" },
      { step: "Architecture", description: "Design data architecture" },
      { step: "Pipeline Build", description: "Build ETL/ELT pipelines" },
      { step: "Testing", description: "Ensure data quality" },
      { step: "Deployment", description: "Deploy and monitor" },
    ],
    benefits: [
      "Real-time data processing",
      "Improved data quality",
      "Scalable to petabytes",
      "Reduced data costs",
    ],
    pricing: "Starting from $4,000",
    duration: "4-10 weeks",
  },
  {
    id: 7,
    slug: "data-analytics",
    title: "Data Analytics",
    shortTitle: "Analytics",
    category: "Analytics",
    description: "Gain valuable insights and optimize decisions through advanced analytics and dashboards.",
    longDescription: "We help you make data-driven decisions with beautiful dashboards, custom reports, and advanced analytics that uncover hidden opportunities.",
    icon: "📊",
    color: "from-teal-500 via-cyan-500 to-blue-600",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
    features: [
      "Business intelligence dashboards",
      "Custom reporting",
      "KPI tracking",
      "Predictive analytics",
      "Customer analytics",
      "Marketing analytics",
      "Financial analytics",
      "Real-time dashboards",
    ],
    technologies: ["Tableau", "Power BI", "Looker", "Metabase", "Python", "SQL"],
    process: [
      { step: "Discovery", description: "Identify key business metrics" },
      { step: "Data Modeling", description: "Structure data for analysis" },
      { step: "Dashboard Build", description: "Create interactive dashboards" },
      { step: "Training", description: "Train your team" },
      { step: "Support", description: "Ongoing analytics support" },
    ],
    benefits: [
      "Data-driven decision making",
      "Real-time business insights",
      "Identify growth opportunities",
      "Reduce reporting time by 80%",
    ],
    pricing: "Starting from $2,500",
    duration: "3-8 weeks",
  },
  {
    id: 8,
    slug: "e-commerce-solutions",
    title: "E-Commerce Solutions",
    shortTitle: "E-Commerce",
    category: "E-Commerce",
    description: "Build powerful online stores with secure payments, inventory, and customer management.",
    longDescription: "We build custom e-commerce solutions and optimize existing stores to maximize sales, conversions, and customer satisfaction.",
    icon: "🛒",
    color: "from-amber-500 via-orange-500 to-red-600",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80",
    features: [
      "Custom online stores",
      "Shopify/WooCommerce development",
      "Payment gateway integration",
      "Inventory management",
      "Order tracking",
      "Multi-currency support",
      "Product catalog",
      "Customer management",
    ],
    technologies: ["Next.js", "Shopify", "Stripe", "WooCommerce", "Medusa", "Snipcart"],
    process: [
      { step: "Strategy", description: "Define e-commerce goals" },
      { step: "Design", description: "Design conversion-optimized UI" },
      { step: "Development", description: "Build the store" },
      { step: "Payment Setup", description: "Integrate payment gateways" },
      { step: "Launch", description: "Go live and optimize" },
    ],
    benefits: [
      "Increase conversions by 150%",
      "Secure payment processing",
      "Mobile-optimized shopping",
      "Analytics-driven insights",
    ],
    pricing: "Starting from $3,500",
    duration: "4-10 weeks",
  },
  {
    id: 9,
    slug: "blockchain-web3",
    title: "Blockchain & Web3",
    shortTitle: "Blockchain",
    category: "Blockchain",
    description: "Smart contracts, dApps, and NFT platforms built on secure, decentralized networks.",
    longDescription: "We develop blockchain applications and smart contracts for DeFi, NFTs, and Web3 platforms that are secure, scalable, and user-friendly.",
    icon: "🔗",
    color: "from-indigo-600 via-purple-600 to-violet-700",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&q=80",
    features: [
      "Smart contract development",
      "DeFi applications",
      "NFT marketplaces",
      "Crypto wallets",
      "Token creation",
      "DApp development",
      "Blockchain integration",
      "Security audits",
    ],
    technologies: ["Solidity", "Ethereum", "Polygon", "Web3.js", "Hardhat", "IPFS"],
    process: [
      { step: "Consultation", description: "Define blockchain use case" },
      { step: "Architecture", description: "Design smart contract architecture" },
      { step: "Development", description: "Build contracts and dApps" },
      { step: "Audit", description: "Security audit and testing" },
      { step: "Deployment", description: "Deploy to mainnet" },
    ],
    benefits: [
      "Secure and audited contracts",
      "Decentralized architecture",
      "Transparent transactions",
      "Future-proof technology",
    ],
    pricing: "Starting from $6,000",
    duration: "6-16 weeks",
  },
  {
    id: 10,
    slug: "cyber-security",
    title: "Cyber Security",
    shortTitle: "Security",
    category: "Security",
    description: "Protect your business with penetration testing, encryption, and security audits.",
    longDescription: "We secure your digital assets with comprehensive security assessments, penetration testing, and ongoing monitoring to protect against evolving threats.",
    icon: "🛡️",
    color: "from-red-500 via-rose-500 to-pink-600",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&q=80",
    features: [
      "Penetration testing",
      "Security audits",
      "Vulnerability assessment",
      "Encryption implementation",
      "Security monitoring",
      "Incident response",
      "Compliance (GDPR, HIPAA)",
      "Security training",
    ],
    technologies: ["Burp Suite", "Metasploit", "Wireshark", "OWASP", "Kali Linux", "Nessus"],
    process: [
      { step: "Assessment", description: "Review current security posture" },
      { step: "Testing", description: "Conduct penetration tests" },
      { step: "Reporting", description: "Document vulnerabilities" },
      { step: "Remediation", description: "Fix security issues" },
      { step: "Monitoring", description: "Ongoing security monitoring" },
    ],
    benefits: [
      "Protect sensitive data",
      "Meet compliance requirements",
      "Prevent costly breaches",
      "Build customer trust",
    ],
    pricing: "Starting from $3,000",
    duration: "2-6 weeks",
  },
  {
    id: 11,
    slug: "qa-testing",
    title: "QA & Testing",
    shortTitle: "QA & Testing",
    category: "QA",
    description: "Ensure bug-free software with automated testing, performance, and security QA.",
    longDescription: "We provide comprehensive quality assurance services including manual testing, test automation, performance testing, and security testing.",
    icon: "🧪",
    color: "from-lime-500 via-green-500 to-emerald-600",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80",
    features: [
      "Manual testing",
      "Test automation",
      "Performance testing",
      "Security testing",
      "Mobile app testing",
      "API testing",
      "Regression testing",
      "Load testing",
    ],
    technologies: ["Selenium", "Cypress", "Playwright", "Jest", "JMeter", "Postman"],
    process: [
      { step: "Planning", description: "Define test strategy" },
      { step: "Test Cases", description: "Write detailed test cases" },
      { step: "Execution", description: "Run manual and automated tests" },
      { step: "Reporting", description: "Document bugs and issues" },
      { step: "Verification", description: "Verify fixes and regression" },
    ],
    benefits: [
      "Catch bugs before production",
      "Reduce development costs",
      "Faster release cycles",
      "Higher customer satisfaction",
    ],
    pricing: "Starting from $2,000",
    duration: "2-8 weeks",
  },
  {
    id: 12,
    slug: "custom-software",
    title: "Custom Software",
    shortTitle: "Custom Software",
    category: "Custom",
    description: "Tailor-made software solutions designed to solve your unique business challenges.",
    longDescription: "We build custom software solutions from scratch — from internal tools and enterprise applications to industry-specific platforms that give you a competitive edge.",
    icon: "⚙️",
    color: "from-slate-600 via-gray-700 to-zinc-800",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&q=80",
    features: [
      "Requirements analysis",
      "Custom application development",
      "Third-party integrations",
      "Legacy system modernization",
      "API development",
      "Database design",
      "User training",
      "Ongoing maintenance",
    ],
    technologies: ["Next.js", "Node.js", "PostgreSQL", "MongoDB", "Docker", "AWS"],
    process: [
      { step: "Discovery", description: "Understand business requirements" },
      { step: "Planning", description: "Create technical roadmap" },
      { step: "Development", description: "Build custom software" },
      { step: "Testing", description: "Comprehensive QA" },
      { step: "Support", description: "Ongoing maintenance" },
    ],
    benefits: [
      "Perfect fit for your workflow",
      "Competitive advantage",
      "Scalable architecture",
      "Full ownership",
    ],
    pricing: "Starting from $5,000",
    duration: "6-20 weeks",
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}